version: '3.8'

name: "carstier"
services:
  postgres:
    container_name: "postgresql"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Auction
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/pgdata:/var/lib/postgresql/data

  mongo:
    container_name: "mongo"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongo/data
      - ./data/mongodata:/var/lib/mongo/data

volumes:
  pgdata:
  mongodata:
